colorScheme = "slate"
autoSwitchAppearance = "false"
smartTOC = true
enableEmoji = true
mainSections = ["adult-books", "workshops", "children-books"]
defaultSocialImage = "img/logo.png"
# defaultAppearance = "dark"
# logo = "img/logo.png"

[homepage]
cardView = true
cardViewScreenWidth = false
showRecent = true
showRecentItems = 20 
layout = "profile"

[article]
showDate = false
showWordCount = false
showAuthor = false
showTableOfContents = true
showTaxonomies = true

[list]
groupByYear = false
cardView = true

[footer]
showThemeAttribution = false

[taxonomy]
heroStyle = "basic"
showHero = true
